# Delete these routes and define your own shop routes here

wemea_sylius_menu_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Wemea\SyliusMenuPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

wemea_sylius_menu_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Wemea\SyliusMenuPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
